version: '3'

services:
  yunzai-web:
    image: registry.cn-hangzhou.aliyuncs.com/117503445-mirror/yunzai-web
    container_name: yunzai-web
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data/yunzai-web/yunzai-bot-data:/workspace/Yunzai-Bot/data # data of `Yunzai-Bot`
      - ./data/yunzai-web/be-images:/workspace/Yunzai-Bot/web-data/images # images of backend

      - ./config/plugins:/workspace/Yunzai-Bot/user_plugins # plugins of `Yunzai-Bot`
      # - ./config/config.json:/workspace/Yunzai-Bot/config.json # config of backend, unconment this line when config.json is provided

      - ./dev-data/vsc:/root/.vscode-server # vscode-server cache
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/117503445-mirror/redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/logs:/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s