FROM 117503445/dev-front

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN yay -S google-chrome --noconfirm

ENTRYPOINT [ "zsh" ]