version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
      
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    # Overrides default command so things don't shut down after the process ends.
    # entrypoint: /usr/local/share/docker-init.sh
    # command: sleep infinity 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./_data/redis/data:/data
      - ./_data/redis/logs:/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s
