version: '3'

services:
  yunzai-web-dev:
    build:
      context: ../../
      dockerfile: doc/docker/Dockerfile
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    volumes:
      - ./dev-data/yunzai-web/data:/root/Yunzai-Bot/data
      - ./dev-data/yunzai-web/web-data/images:/root/Yunzai-Bot/web-data/images
  redis:
    # docker pull registry.cn-hangzhou.aliyuncs.com/117503445-mirror/redis:alpine && docker image tag registry.cn-hangzhou.aliyuncs.com/117503445-mirror/redis:alpine redis:alpine
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/logs:/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s