version: '3'

services:
  yunzai-web-dev:
    build:
      context: ../../
      dockerfile: doc/docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    # ports:
    #   - 8080:8080
    volumes:
      - ./data/yunzai-web/yunzai-bot-data:/workspace/Yunzai-Bot/data # data of `Yunzai-Bot`
      - ./data/yunzai-web/be-images:/workspace/Yunzai-Bot/web-data/images # images of backend

      # - ./config/config.json:/workspace/Yunzai-Bot/config.json # config of backend
      - ./config/plugins:/workspace/Yunzai-Bot/user_plugins

      - ../../src/Yunzai-Bot/docker-entrypoint.py:/workspace/Yunzai-Bot/docker-entrypoint.py

      - ./dev-data/vsc:/root/.vscode-server # vscode-server cache


  redis:
    # docker pull registry.cn-hangzhou.aliyuncs.com/117503445-mirror/redis:alpine && docker image tag registry.cn-hangzhou.aliyuncs.com/117503445-mirror/redis:alpine redis:alpine
    image: redis:alpine
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/logs:/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s